config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :complaints, except: [:create]
  resources :companies do
  resources :complaints
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'companies#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :complaints, dependent: :destroy
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  has_many :complaints, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, only: [:show]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    @company = Company.new
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @complaint = Complaint.new
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
        format.js
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_path, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
      @complaint = Complaint.new(complaint_params)
      @complaint.user = current_user
      @complaint.company_id = params[:company_id]
      respond_to do |format|
        if @complaint.save
          format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
          format.json { render :show, status: :created, location: @complaint }
          format.js {}
        else
          format.html { render :new }
          format.json { render json: @complaint.errors, status: :unprocessable_entity }
        end
      end
    end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:user_id, :company_id, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/companies/_company.html.erb
<tr id="company_<%= company.id %>">
  <td><%= company.name %></td>
  <td><%= link_to 'Show', company, class:"btn btn-info" %></td>
  <td><%= link_to 'Edit', edit_company_path(company), data: { remote: true}, class:"btn btn-primary" %></td>
  <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?',remote: true }, class:"btn btn-dark" %></td>
</tr>

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/create.js.erb
$('table > tbody:last-child').append('<%= j render @company %>');

app/views/companies/destroy.js.erb
$('#company_<%= @company.id%>').toggle();

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company, class:"btn btn-info" %>
<%= link_to 'Back', companies_path, class:"btn btn-warning" %>

app/views/companies/edit.js.erb
$('.modal-body').html("<%= j render 'form', company: @company %>")
$('#myModal').modal('show');

app/views/companies/index.html.erb
<h1>Companies</h1>
<%= render 'form', company:@company %>
<table class="table">
   <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @companies %>
  </tbody>
</table>

<br>


<div class="modal" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<%= link_to 'New Company', new_company_path, class:"btn btn-secondary"  %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path, class:"btn btn-warning" %>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<ul id="reclamo">
<%= render 'complaints/form', complaint: @complaint, company: @company %>
<% @company.complaints.order(created_at: :desc).each do |complaint| %>
  <li><%= complaint.content %>
  <%= complaint.user.email %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_company_path(@company), class:"btn btn-primary" %>
<%= link_to 'Back', companies_path, class:"btn btn-warning"%>

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, url: company_complaints_url(company.id)) do |form| %>

  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
        <% complaint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/complaints/create.js.erb
$('#reclamo').prepend('<li> <%= @complaint.content %> <%= @complaint.user.email %> </li>');

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', company: @complaint.company, complaint: @complaint %>

<%= link_to 'Show', @complaint, class:"btn btn-info" %>
<%= link_to 'Back', complaints_path, class:"btn btn-warning" %>

app/views/complaints/index.html.erb
<h1>Complaints</h1>

<table class="table">
   <thead class="thead-dark">
    <tr>
      <th>User</th>
      <th>Company</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.user_id %></td>
        <td><%= complaint.company_id %></td>
        <td><%= complaint.content %></td>
        <td><%= link_to 'Show', complaint, class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path, class:"btn btn-secondary" %>

app/views/complaints/new.html.erb
<h1>New Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Back', complaints_path, class:"btn btn-warning" %>

app/views/complaints/show.html.erb
<p>
  <strong>User:</strong>
  <%= @complaint.user_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @complaint.company_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @complaint.content %>
</p>


<%= link_to 'Edit', edit_complaint_path(@complaint), class:"btn btn-primary" %>
<%= link_to 'Back', complaints_path, class:"btn btn-warning" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba5ajax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'shared/navbar'%>
    <div class="container">
      <%= render 'shared/alert'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_navbar.html.erb
<ul class="nav justify-content-end navbar-dark bg-dark">
  <% if user_signed_in?%>
  <li class="nav-item">
    <a class="nav-link"><%= current_user.email %></a>
  </li>
  <li class="nav-item">
    <%= link_to "Lista", root_path, class: 'nav-link'%>
  </li>
  <li class="nav-item">
    <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'nav-link'%>
  </li>
  <% else %>
  <li class="nav-item">
    <%= link_to "Iniciar Sesión", new_user_session_path, class: 'nav-link'%>
  </li>
  <li class="nav-item">
    <%= link_to "Registro", new_user_registration_path, class: 'nav-link'%>
  </li>
  <% end %>
</ul>